spring:
  datasource:
    url: jdbc:mariadb://localhost:7777/mydb
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: lifemmo123!@#
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8080

